set encoding=utf-8
set fileencodings=utf-8,chinese,latin-1,ucs-bom,cp936
set termencoding=utf-8
set fileencoding=utf-8 
set langmenu=en_US
set nocompatible
set number
set ignorecase
set smartcase
set incsearch
set autoindent
set smartindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
colorscheme molokai
let g:molokai_original = 1
filetype on 
syntax on 
set history=2000 
set cindent 
set showmatch 
set vb t_vb= 
set ruler 
set hlsearch 
set scrolloff=3 
set nowrap 
set pastetoggle=<F4>
